services:
  mydesktop:
    container_name: mydesktop
    hostname: mydesktop
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./server/config:/app/config
    environment:
      - NODE_ENV=production
      - PORT=4000
      - API_BASE_URL=http://192.168.1.202:4000
    restart: unless-stopped
