
desktop:
  background:
    style: image
    colors:
      - "hsla(280, 80%, 70%, 1)"
      - "hsla(200, 90%, 65%, 1)"
      - "hsla(330, 80%, 75%, 1)"
      - "hsla(40, 90%, 70%, 1)"
    src: "https://sleepingbearhotels.com/wp-content/uploads/2025/05/Where-Is-Durdle-Door.webp"
    color: "#d6d3ff"
  foreground:
    color: "#000000"

layout:
  columns: 12
  components:
    - name: Clock
      type: widget
      component: UIAnalogClock
      props:
        timezone: "Europe/London"

    - name: "Pi-Hole"
      type: app-icon
      component: UIAppIconLink
      props:
        label: "Pi-Hole"
        url: "http://192.168.1.202:3000/admin"
        icon: "pi-hole"

    - name: "File browser"
      type: app-icon
      component: UIAppIconLink
      props:
        label: "File Browser"
        url: "https://6d26316a6dcf.duckdns.org/login?redirect=/files/"
        icon: "file-browser"

    - name: "Jellyfin"
      type: app-icon
      component: UIAppIconLink
      props:
        label: "Jellyfin"
        url: "http://192.168.1.202:8096/"
        icon: "jellyfin"

    - name: "arr"
      type: folder
      props:
        label: "Arrr"
        icon: "file-explorer"
      components:
        - name: "Prowlarr"
          type: app-icon
          component: UIAppIconLink
          props:
            label: "Prowlarr"
            url: "http://192.168.1.213:9696"
            icon: "prowlarr"

        - name: "Jellyseerr"
          type: app-icon
          component: UIAppIconLink
          props:
            label: "Jellyseerr"
            url: "http://192.168.1.210:5055/login"
            icon: "jellyseerr"

        - name: "Radarr"
          type: app-icon
          component: UIAppIconLink
          props:
            label: "Radarr"
            url: "http://192.168.1.214:7878"
            icon: "radarr"

        - name: "Lidarr"
          type: app-icon
          component: UIAppIconLink
          props:
            label: "Lidarr"
            url: "http://192.168.1.212:8686"
            icon: "lidarr"

        - name: "QBittorrent"
          type: app-icon
          component: UIAppIconLink
          props:
            label: "QBittorrent"
            url: "http://192.168.1.211:8080"
            icon: "qbittorrent"

    - name: "vopidy"
      type: app-icon
      component: UIAppIconLink
      props:
        label: "Vopidy"
        url: "https://0875ce890ad6.duckdns.org"
        icon: "spotify"

    - name: Weather
      type: custom
      component: UIWeatherWidget
      props:
        location: "current"

    - name: News
      type: custom
      component: UINewsHeadlinesWidget
      props:
        rss: "https://feeds.bbci.co.uk/news/rss.xml"
        size: "medium"

    - name: Moon Phase
      type: custom
      component: UISunMoonPhaseWidget
      props:
        location: "current"

    - name: SystemInfo
      type: custom
      component: UISystemInfoWidget
      props:
        location: "current"

    - name: Map
      type: custom
      component: UIMapWidget
      props:
        location: "current"

    - name: Calendar
      type: custom
      component: UICalendarWidget
      props:
        location: "current"

    - name: AudioPlayer
      type: custom
      component: UIAudioPlayer
      props:
        track:
          artist: "Queen"
          title: "One Vision"
          src: "https://files.freemusicarchive.org/storage-freemusicarchive-org/music/WFMU/Broke_For_Free/Directionless_EP/Broke_For_Free_-_01_-_Night_Owl.mp3"
